### ISSUE TITLE
GitHub OAuth for the user authentication

### ISSUE THREAD

**Issue by droud-dev** [jaspreet338/tech-pandas-STAR#2]
We need to use [GitHub's OAuth implementation](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow) in order to authenticate users

Prerequirements:
- Have a GitHub app ([documentation](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app))

User flow:
1. User clicks on `Login/Register` button
  - This can be the `href` property on the `a` element that acts as the button
2. User gets redirected to the GitHub login page
3. After authentication, the user gets redirected to the STAR app
4. After redirection to the app, the backend for that page needs to make a `POST` request to the GitHub API to get the authentication and refresh tokens
5. Once the backend has received those tokens, they need to be stored in the `User` database, associated with the unique GitHub username, as well as `localStorage` in the Frontend so that the Dashboard knows that the user has been authenticated
6. Once the Authentication Token is stored in `localStorage`, the user should be redirected:
  - to the Dashboard page *IF* the user already exists
  - to the Register page *IF* the user does not exist

**Comment by TsioneTemesgenAbraham** [comment]
Blocked until Dashboard page is available.
